[tool.poetry]
name = "lodestone"
version = "0.0.7"
description = "🤖 Create Minecraft bots with a powerful, stable, and high level Python API."
authors = [
    "Silke pilon <silkepilon2009@gmail.com>",
    "HellishBro (README.js) <@812125215051743282> on Discord"
]
license = "MIT"
readme = "README.md"

